bot:
  # Fill with your Discord bot token
  token:
  commands:
    media_group:
      name: meme
      commands:
        get:
          description: Get a random meme
        periodic:
          enable:
            description: Send periodic memes
            autocomplete_hint: How often memes should be sent in minutes
          disable:
            description: Stop periodic memes
    text_group:
      name: copypasta
      commands:
        get:
          description: Get a random copypasta
        deep_fry_text:
          description: Get a random deep-fried copypasta
      language_subgroup:
        commands:
          set:
            description: Set language for copypastas
            autocomplete_hint: Output language for copypastas
          reset:
            description: Reset language for copypastas

sources:
  # Sources are stored in a mounted volume, not the container itself
  file: /config/custom_sources.yml

db:
  # Discord channel data DB is stored in a mounted volume, not the container itself
  path: /config/channel_data.db
