media:
  - url: http://reddit-api-api:8080/subreddit/media/random/2meirl4meirl/20
    keys: [media_url]
  - url: http://reddit-api-api:8080/subreddit/media/random/whenthe/20
    keys: [media_url]
  - url: http://reddit-api-api:8080/subreddit/media/random/surrealmemes/20
    keys: [media_url]
  - url: http://reddit-api-api:8080/subreddit/media/random/deepfriedsurrealmemes/20
    keys: [media_url]
  - url: http://reddit-api-api:8080/subreddit/media/random/moistmemes/20
    keys: [media_url]
  - url: http://reddit-api-api:8080/subreddit/media/random/dankvideos/20
    keys: [media_url]

text:
  - url: http://reddit-api-api:8080/subreddit/text/random/copypasta/20
    keys: [selftext]
    language: en
